---
title: "p8105_hw5_mnw2132"
author: "Mary Williams"
date: "2024-11-15"
output: github_document
---
# Set up 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries}
library(tidyverse)
library(ggplot2)
library(rvest)
library(broom)
```

# Problem 1
### Create the function
```{r}
#Create the function
birthday_data<-function(sample_size) {
  bday<- sample(1:365, sample_size, replace = TRUE)
  any(duplicated(bday))
}
```


```{r}
# Run the function
sim_bday= 
  tibble(
    sample_size = 2:50) %>%
  mutate(
    output_lists = map(.x = sample_size, ~rerun(10000, birthday_data(.x))), 
    estimate_df= map_dbl(output_lists, ~mean(unlist(.)))
) %>%
  select(sample_size, estimate_df)
```
### Graph the function
```{r}
sim_bday %>%
  ggplot(aes(x = sample_size, y = estimate_df)) +   geom_line(color = "light pink") +  geom_point(color = "red") + 
  labs(
    x = "Sample Size",
    y = "Probability of Duplicate Birthday",
    title = "Probability that ≥2 Share a Birthday") + 
theme_minimal()
```

# Problem 2
```{r}
set.seed(1)

#Create the function 
t_test = function(n = 30, mu = 0, sigma = 5) {
  sim_test = tibble(
    x = rnorm(n, mean = mu, sd = sigma))
  
  test_result = t.test(sim_test$x, mu = 0)
  tidy_result = tidy(test_result)
  
  tibble(
    mu_hat = mean(sim_test$x),
    p_value = tidy_result$p.value
  )
}

t_test(30)
```

```{r}
sim_results = map_dfr(c(0, 1, 2, 3, 4, 5, 6), function(mu) {
  map_dfr(1:5000, ~ t_test(n = 30, mu = mu, sigma = 5))
})
```

